[package]
authors = ["Garrett Berg <googberg@gmail.com>"]
name = "ergo_config"
version = "0.1.0"

[dependencies]
configure = "0.1.1"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serde_yaml = "0.7.3"
toml = "0.4.5"
