[package]
authors = ["Garrett Berg <googberg@gmail.com>"]
name = "ergo_sync"
version = "0.1.0"

[dependencies]
crossbeam-channel = "0.1.2"
num_cpus = "1.8.0"
std_prelude = "0.2.11"
taken = "0.1.0"

[dev-dependencies]
rayon = "0.9.0"
crossbeam-utils = "0.2.2"
