[package]
authors = ["Garrett Berg <vitiral@gmail.com>"]
description = "<pre-alpha> making rust's ecosystem more ergonomic, therefore more fun."
documentation = "https://docs.rs/ergo"
keywords = [
    "ergonomics",
]
license = "MIT OR Apache-2.0"
name = "ergo"
readme = "README.md"
repository = "https://github.com/rust-crates/ergo"
version = "0.1.2"
