[package]
authors = ["Garrett Berg <googberg@gmail.com>"]
name = "ergo_prelude"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
itertools = "0.7.6"
lazy_static = "1.0.0"
maplit = "1.0.1"
ordermap = "0.3.5"
std_prelude = "0.2.11"
